---
name: Test-DistManifest
version: 1.006
author:
  - 'Jonathan Yu <jawnsy@cpan.org>'
abstract: Author test that validates a package MANIFEST
license: perl
resources:
  Ratings: http://cpanratings.perl.org/d/Test-DistManifest
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=Test-DistManifest
  license: http://dev.perl.org/licenses/
  repository: http://svn.ali.as/cpan/trunk/Test-DistManifest
build_requires:
  Test::Builder::Tester: 0
  Test::NoWarnings: 0.084
requires:
  Module::Manifest: 0.07
  Test::Builder: 0.72
  Test::More: 0.62
  perl: 5.006
configure_requires:
  Module::Build: 0.35
dynamic_config: 0
provides:
  Test::DistManifest:
    file: lib/Test/DistManifest.pm
    version: 1.006
generated_by: Module::Build version 0.35
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
